/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPack;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class FrmViewDataset extends javax.swing.JFrame {

    /**
     * Creates new form FrmViewDataset
     */
    MainForm parent;
    Object colHeader[];
    DefaultTableModel tm;
    public FrmViewDataset(MainForm parent) {
        this.parent = parent;
        initComponents();
        Dimension sd  = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(sd.width / 2 - this.getWidth()/ 2, sd.height / 2 - this.getHeight()/ 2); 
        //colHeader = new Object[]{"AGE","SEX","HBA1C","RESTING BP","PLASMA GLUCOSE","CHLORESTROL","HEMOGLOBIN","PULSE RATE","HYPERTENSION","HEREDITORI","SEIZER ATTACK","FOOT ULCERS","HEAD INJURY","BACTERIAL MENINGITIS","VIRAL DISEASE","PREDICTION","MEDICINES"};
                //colHeader = new Object[]{"AGE","SEX","HBA1C","RESTING BP","PLASMA GLUCOSE","CHLORESTROL","DATE","PULSE RATE","HYPERTENSION","HEREDITORY","SEIZER ATTACK","FOOT ULCERS","HEAD INJURY","BACTERIAL MENINGITIS","VIRAL DISEASE","SEVERITY INDEX","TREATMENT"};
             colHeader = new Object[]{"AGE","SEX","HBA1C","RESTING BP","PLASMA GLUCOSE","CHLORESTROL","DATE","PULSE RATE","HYPERTENSION","HEREDITORY","FOOT ULCERS","SEVERITY INDEX","TREATMENT"};
        tm = new DefaultTableModel(colHeader, 0);
        
        fillTable();
    }

    
     void fillTable(){
        for(int i=0;i<parent.dataSet.dataSet.size();i++){
            String s[] = new String[16];
            
            s[0] = parent.attributes[0][parent.dataSet.dataSet.elementAt(i).dataItem[0]];
            s[1] = parent.attributes[1][parent.dataSet.dataSet.elementAt(i).dataItem[1]];
             s[2] = parent.dataSet.dataSet.elementAt(i).descr[2];
            s[3] = parent.attributes[3][parent.dataSet.dataSet.elementAt(i).dataItem[3]];
            s[4] = parent.attributes[4][parent.dataSet.dataSet.elementAt(i).dataItem[4]];
            s[5] = parent.attributes[5][parent.dataSet.dataSet.elementAt(i).dataItem[5]];
//             s[6] = parent.attributes[6][parent.dataSet.dataSet.elementAt(i).dataItem[6]];
             String str="";//parent.dataSet.dataSet.elementAt(i).descr[6].substring(0,1);
             String str1="";//parent.dataSet.dataSet.elementAt(i).descr[6].substring(1);
             System.out.println("parent.dataSet.dataSet.elementAt(i).descr[6] = "+parent.dataSet.dataSet.elementAt(i).descr[6]);
              if(parent.dataSet.dataSet.elementAt(i).descr[6].length()==4){
                        str=parent.dataSet.dataSet.elementAt(i).descr[6].substring(0,2);
                        System.out.println("str="+str);
                        str1=parent.dataSet.dataSet.elementAt(i).descr[6].substring(2,2);
                        }else{
                         str=parent.dataSet.dataSet.elementAt(i).descr[6].substring(0,1);
                         System.out.println("str="+str);
                         str1=parent.dataSet.dataSet.elementAt(i).descr[6].substring(1,2);
                        }
              if(str1.equals("0"))
                  str1="1";
            s[6] = str1+"-"+str+"-2014";
            s[7] = parent.dataSet.dataSet.elementAt(i).descr[7];
            s[8] = parent.attributes[7][parent.dataSet.dataSet.elementAt(i).dataItem[7]];
            s[9] = parent.dataSet.dataSet.elementAt(i).descr[9];
      //       s[10] = parent.attributes[8][parent.dataSet.dataSet.elementAt(i).dataItem[8]];
            s[10] = parent.dataSet.dataSet.elementAt(i).descr[11];
             //s[11] = parent.attributes[9][parent.dataSet.dataSet.elementAt(i).dataItem[9]];
            s[11] = parent.dataSet.dataSet.elementAt(i).descr[15];
            s[12] =parent.medicines[Integer.parseInt(s[11])];
           // s[13] = parent.attributes[10][parent.dataSet.dataSet.elementAt(i).dataItem[10]];
            String date=parent.dataSet.dataSet.elementAt(i).descr[6];
            int count=DatabaseConnection.executeUpdate("insert into dataset values('"+s[0]+"','"+s[1]+"','"+s[2]+"','"+s[3]+"','"+s[4]+"','"+s[5]+"','"+s[6]+"','"+s[7]+"','"+s[8]+"','"+s[9]+"','"+s[10]+"','"+s[11]+"','"+s[12]+"','"+s[13]+"','"+s[14]+"','"+s[15]+"')");
            System.out.println("insert into dataset values('"+s[0]+"','"+s[1]+"','"+s[2]+"','"+s[3]+"','"+s[4]+"','"+s[5]+"','"+s[6]+"','"+s[7]+"','"+s[8]+"','"+s[9]+"','"+s[10]+"','"+s[11]+"','"+s[12]+"','"+s[13]+"','"+s[14]+"','"+s[15]+"')");
            System.out.println("Count == "+count);
            tm.addRow(s);
        }
        jTable1.setModel(tm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        new JavaLib.LoadForm();
        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mining Signatures from Event Sequences and ");

        new JavaLib.LoadForm();
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPack/heart.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        new JavaLib.LoadForm();
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("View Dataset");

        new JavaLib.LoadForm();

        new JavaLib.LoadForm();
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 795, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 423, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(430, 430, 430))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
